### ISSUE TITLE
list index out of range for ssl_connections[0].keys()

### ISSUE THREAD

**Issue by dhaniyapatta** [clay584/whatls#4]
I captured TLS in a pcap file. (If I open the file in Wireshark, I can see TLSv1.2 packets). But on running whatls.py, I am getting the list index out of range error

**Comment by clay584** [comment]
Can you attach the trace back so I can see where it crashed? Also, if you can attach the pcap as well, that would help.

**Comment by dhaniyapatta** [comment]
This  is the error i am getting. I have attached the pcap file

[image: 2021-12-10_14-22.png]

**Comment by dhaniyapatta** [comment]
https://drive.google.com/drive/folders/1MDK3NuYY5X-70AHBuKrI3RisDFXcED3i?usp=sharing

I have added the error and the pcap file

**Comment by clay584** [comment]
Ok, I fixed it. It looks like either pyshark changed the packet API from `ssl` to `tls` or the file format output by wireshark is somehow different. Not quite sure. The original code is in the `ssl` branch, and the fixed code for `tls` is on the master branch.

In order to update your code and use it, do the following:

1. `git pull`
2. `sudo apt update && apt install tshark`
3. `pip install -r requirements.txt`
4. `tcpdump -nt -r new_cap.pcap "$(cat ssl_filter.bpf)" -w new_cap_filtered.pcap`
5. `./whatls.py new_cap_filtered.pcap`

That will output the attached CSV file.
[new_cap_filtered.csv](https://github.com/clay584/whatls/files/7693668/new_cap_filtered.csv)
